
# Chargement de l'ensemble des packages utiles pour ce projet:

library(readr)
library(HMDHFDplus)
library(tibble)
library(dplyr)
library(tidyr)
library(esquisse)
library(ggplot2)
library(ggpubr)
library(forcats)
library(ggrepel)
library(car)
library(survival)
library(eha)
library(sfsmisc)
library(goeveg)
library(PerformanceAnalytics)

library(GGally) 
library(performance)
library(see)
library(patchwork)
library(corrplot)
library(gplots)
library(lmtest)
library(rstatix)

library(FactoMineR)
library(factoextra)
library(FactoInvestigate)
library(Factoshiny)
